# .github/workflows/ci.yml
name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - unknown17
  pull_request:
    branches:
      - unknown17 

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: task_api
  DOCKER_IMAGE_TAG: latest

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx create --use --name mybuilder
        docker buildx build --platform linux/amd64,linux/arm64 --push -t "${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" .
