name: Build, Push and Deploy Docker Image

on:
  push:
    branches: [ "unknown17" ]
  pull_request:
    branches: [ "unknown17" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: task_API
  DOCKER_IMAGE_TAG: latest

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        # Wait for MongoDB to be ready
        docker-compose -f docker-compose.yml exec -T mongodb mongo --eval "db.runCommand({ ping: 1 })"
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v ./...

    - name: Test specific file
      run: go test -v ./handler_test.go

    - name: Login to Docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx create --use --name mybuilder
        docker buildx build --platform linux/amd64,linux/arm64 --push -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
